import avatar1 from '../../../../assets/images/users/avatar-6.jpg';
import avatar2 from '../../../../assets/images/users/avatar-7.jpg';
import avatar3 from '../../../../assets/images/users/avatar-8.jpg';

const GlobalActividades = [
    {
        id: 1,
        codmateria: '0252',
        items: 'MIS ACTIVIDADES SIN ENVIAR',
        pendiente: '42',
        porcentaje: '5.27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Danger',
        color: 'danger',
        selected: '2',
        status: 'Pending',
    },
    {
        id: 2,
        codmateria: '0252',
        items: 'MIS ACTIVIDADES ENVIADAS',
        pendiente: '12',
        porcentaje: '100%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Success',
        color: 'success',
        selected: '2',
        status: 'Done',
    },
    {
        id: 3,
        codmateria: '0252',
        items: 'MIS CURSOS',
        pendiente: '22',
        porcentaje: '27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Warning',
        color: 'warning',
        selected: '2',
        status: 'Cursos',
    },
    {
        id: 4,
        codmateria: '0252',
        items: 'MIS VIDEOS DE CLASES',
        pendiente: '20',
        porcentaje: '0%',
        classe: 'text-warning',
        observacion: 'No tiene Actividades por entregar',
        name: 'Secondary',
        color: 'secondary',
        selected: '2',
        status: 'Videos',
    },

    //5011
    {
        id: 1,
        codmateria: '5011',
        items: 'MIS ACTIVIDADES SIN ENVIAR',
        pendiente: '54',
        porcentaje: '5.27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Danger',
        color: 'danger',
        selected: '2',
        status: 'Pending',
    },
    {
        id: 2,
        codmateria: '5011',
        items: 'MIS ACTIVIDADES ENVIADAS',
        pendiente: '62',
        porcentaje: '100%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Success',
        color: 'success',
        selected: '2',
        status: 'Done',
    },
    {
        id: 3,
        codmateria: '5011',
        items: 'MIS CURSOS',
        pendiente: '6',
        porcentaje: '27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Warning',
        color: 'warning',
        selected: '2',
        status: 'Cursos',
    },
    {
        id: 4,
        codmateria: '5011',
        items: 'MIS VIDEOS DE CLASES',
        pendiente: '80',
        porcentaje: '0%',
        classe: 'text-warning',
        observacion: 'No tiene Actividades por entregar',
        name: 'Secondary',
        color: 'secondary',
        selected: '2',
        status: 'Videos',
    },
    //515
    {
        id: 1,
        codmateria: '515',
        items: 'MIS ACTIVIDADES SIN ENVIAR',
        pendiente: '7',
        porcentaje: '5.27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Danger',
        color: 'danger',
        selected: '2',
        status: 'Pending',
    },
    {
        id: 2,
        codmateria: '515',
        items: 'MIS ACTIVIDADES ENVIADAS',
        pendiente: '72',
        porcentaje: '100%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Success',
        color: 'success',
        selected: '2',
        status: 'Done',
    },
    {
        id: 3,
        codmateria: '515',
        items: 'MIS CURSOS',
        pendiente: '55',
        porcentaje: '27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Warning',
        color: 'warning',
        selected: '2',
        status: 'Cursos',
    },
    {
        id: 4,
        codmateria: '515',
        items: 'MIS VIDEOS DE CLASES',
        pendiente: '60',
        porcentaje: '0%',
        classe: 'text-warning',
        observacion: 'No tiene Actividades por entregar',
        name: 'Secondary',
        color: 'secondary',
        selected: '2',
        status: 'Videos',
    },
    //0512
    {
        id: 1,
        codmateria: '0512',
        items: 'MIS ACTIVIDADES SIN ENVIAR',
        pendiente: '46',
        porcentaje: '5.27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Danger',
        color: 'danger',
        selected: '2',
        status: 'Pending',
    },
    {
        id: 2,
        codmateria: '0512',
        items: 'MIS ACTIVIDADES ENVIADAS',
        pendiente: '82',
        porcentaje: '100%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Success',
        color: 'success',
        selected: '2',
        status: 'Done',
    },
    {
        id: 3,
        codmateria: '0512',
        items: 'MIS CURSOS',
        pendiente: '282',
        porcentaje: '27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Warning',
        color: 'warning',
        selected: '2',
        status: 'Cursos',
    },
    {
        id: 4,
        codmateria: '0512',
        items: 'MIS VIDEOS DE CLASES',
        pendiente: '80',
        porcentaje: '0%',
        classe: 'text-warning',
        observacion: 'No tiene Actividades por entregar',
        name: 'Secondary',
        color: 'secondary',
        selected: '2',
        status: 'Videos',
    },
    //0516
    {
        id: 1,
        codmateria: '0516',
        items: 'MIS ACTIVIDADES SIN ENVIAR',
        pendiente: '94',
        porcentaje: '5.27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Danger',
        color: 'danger',
        selected: '2',
        status: 'Pending',
    },
    {
        id: 2,
        codmateria: '0516',
        items: 'MIS ACTIVIDADES ENVIADAS',
        pendiente: '29',
        porcentaje: '100%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Success',
        color: 'success',
        selected: '2',
        status: 'Done',
    },
    {
        id: 3,
        codmateria: '0516',
        items: 'MIS CURSOS',
        pendiente: '252',
        porcentaje: '27%',
        classe: 'text-success',
        observacion: 'Tiene Actividades por entregar',
        name: 'Warning',
        color: 'warning',
        selected: '2',
        status: 'Cursos',
    },
    {
        id: 4,
        codmateria: '0516',
        items: 'MIS VIDEOS DE CLASES',
        pendiente: '50',
        porcentaje: '0%',
        classe: 'text-warning',
        observacion: 'No tiene Actividades por entregar',
        name: 'Secondary',
        color: 'secondary',
        selected: '2',
        status: 'Videos',
    },
];

const tasks = [
    {
        id: 1,
        title: 'Normatividad Flora y Fauna',
        codmateria: '0252',
        status: 'Pending',
        priority: 'High',
        userAvatar: avatar1,
        periodo: 'I',
        project: 'taller flora y fauna',
        totalComments: 28,
        totalSubTasks: 10,
        user: 'LUIS ENRIQUE CARRILLO ORTEGA',
        dueDate: 'Jul 18, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
    {
        id: 2,
        title: 'Minton v3.0 - Redesign',
        codmateria: '5011',
        status: 'Inprogress',
        priority: 'Low',
        userAvatar: avatar2,
        project: 'taller flora y fauna',
        periodo: 'I',
        totalComments: 21,
        totalSubTasks: 7,
        user: 'LUIS ENRIQUE CARRILLO ORTEGA',
        dueDate: 'Jul 20, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
    {
        id: 3,
        title: 'Hyper v2.1 - Angular and Django',
        codmateria: '515',
        status: 'Review',
        priority: 'Low',
        userAvatar: avatar1,
        project: 'aller N.M',
        periodo: 'I',
        totalComments: 24,
        totalSubTasks: 2,
        user: 'CoderThemes',
        dueDate: 'Jul 21, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
    {
        id: 4,
        title: 'Hyper v2.1 - React, Webpack',
        codmateria: '515',
        status: 'Done',
        priority: 'High',
        userAvatar: avatar2,
        project: 'Hyper2',
        periodo: 'I',
        totalComments: 21,
        totalSubTasks: 5,
        user: 'CoderThemes2',
        dueDate: 'Jul 22, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
    {
        id: 5,
        title: 'Hyper 2.2 - Vue.Js and Laravel',
        codmateria: '0512',
        status: 'Pending',
        priority: 'Low',
        userAvatar: avatar3,
        project: 'Actividad G4',
        periodo: 'I',
        totalComments: 2,
        totalSubTasks: 0,
        user: 'LUIS ENRIQUE CARRILLO ORTEGA',
        dueDate: 'Jul 18, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
    {
        id: 6,
        title: 'Hyper 2.3 - Rails, NodeJs, Mean',
        codmateria: '0512',
        status: 'Pending',
        priority: 'Medium',
        userAvatar: avatar2,
        project: 'Actividad',
        periodo: 'I',
        totalComments: 24,
        totalSubTasks: 8,
        user: 'LUIS ENRIQUE CARRILLO ORTEGA',
        dueDate: 'Jul 21, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
    {
        id: 7,
        title: 'Hyper - Landing page and UI Kit',
        codmateria: '0512',
        status: 'Review',
        priority: 'Medium',
        userAvatar: avatar3,
        project: 'Hyper',
        periodo: 'I',
        totalComments: 11,
        totalSubTasks: 6,
        user: 'CoderThemes',
        dueDate: 'Jul 10, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
    {
        id: 8,
        title: 'Hyper 3.0 - Scoping',
        codmateria: '0516',
        status: 'Inprogress',
        priority: 'High',
        userAvatar: avatar2,
        project: 'Hyper2',
        periodo: 'I',
        totalComments: 10,
        totalSubTasks: 4,
        user: 'CoderThemes2',
        dueDate: 'Jul 24, 2019',
        description:
            // tslint:disable-next-line: max-line-length
            '<p>This is a task description with markup support</p><ul><li>Select a text to reveal the toolbar.</li><li>Edit rich document on-the-fly, so elastic!</li></ul><p>End of air-mode area</p>',
        attachments: [
            { id: 1, filename: 'sales-assets.zip', size: '2.3 MB' },
            { id: 2, filename: 'new-contarcts.docx', size: '1.3 MB' },
        ],
    },
];

export { GlobalActividades,tasks };
