const users = [
    {
        id_pernatural: '25979',
        id_personas: '25983',
        primer_nombre: 'ORLANDO',
        segundo_nombre: 'ELIAS',
        sexo: 'M',
        primer_apellido: 'GUERRA',
        segundo_apellido: 'GUERRA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1122410021',
        firstName: 'ORLANDO ELIAS',
        lastName: 'GUERRA GUERRA',
        role: 'Estudiante',
        mail: 'ORLANDOGUERRA9402@HOTMAIL.COM',
        email_institucional: 'ORLANDOGUERRA9402@HOTMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26044',
        id_personas: '26048',
        primer_nombre: 'NAYLIS',
        segundo_nombre: 'DIJIRETH',
        sexo: 'F',
        primer_apellido: 'MUNIVE',
        segundo_apellido: 'GONZALES',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1122416865',
        firstName: 'NAYLIS DIJIRETH',
        lastName: 'MUNIVE GONZALES',
        role: 'Estudiante',
        mail: 'NAYLISM07@GMAIL.COM',
        email_institucional: 'NAYLISM07@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26435',
        id_personas: '26437',
        primer_nombre: 'GUSTAVO',
        segundo_nombre: 'ELIAS',
        sexo: 'M',
        primer_apellido: 'MAZZIRI',
        segundo_apellido: 'LOZANO',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1121336669',
        firstName: 'GUSTAVO ELIAS',
        lastName: 'MAZZIRI LOZANO',
        role: 'Estudiante',
        mail: 'GUSTAVOMAZZIRI96@GMAIL.COM',
        email_institucional: 'GUSTAVOMAZZIRI96@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26368',
        id_personas: '26370',
        primer_nombre: 'YANESI',
        segundo_nombre: 'PAOLA',
        sexo: 'F',
        primer_apellido: 'FONSECA',
        segundo_apellido: 'MOLINA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1007626776',
        firstName: 'YANESI PAOLA',
        lastName: 'FONSECA MOLINA',
        role: 'Estudiante',
        mail: 'YAFOMO31@GMAIL.COM',
        email_institucional: 'YAFOMO31@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26431',
        id_personas: '26433',
        primer_nombre: 'JAIDER',
        segundo_nombre: 'JOSé',
        sexo: 'M',
        primer_apellido: 'POLO',
        segundo_apellido: 'MENDOZA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1006735543',
        firstName: 'JAIDER JOSé',
        lastName: 'POLO MENDOZA',
        role: 'Estudiante',
        mail: 'JAIDERJOSEPOLO5@GMAIL.COM',
        email_institucional: 'JAIDERJOSEPOLO5@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26418',
        id_personas: '26420',
        primer_nombre: 'OMAR',
        segundo_nombre: 'DAVID',
        sexo: 'M',
        primer_apellido: 'MONTERO',
        segundo_apellido: 'ANAYA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1004092185',
        firstName: 'OMAR DAVID',
        lastName: 'MONTERO ANAYA',
        role: 'Estudiante',
        mail: 'OMARMONTEANA12@GMAIL.COM',
        email_institucional: 'OMARMONTEANA12@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26270',
        id_personas: '26272',
        primer_nombre: 'ALNEDO',
        segundo_nombre: 'DE JESUS',
        sexo: 'M',
        primer_apellido: 'ZULETA',
        segundo_apellido: 'SANCHEZ',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1118869218',
        firstName: 'ALNEDO DE JESUS',
        lastName: 'ZULETA SANCHEZ',
        role: 'Estudiante',
        mail: 'ALNEDO18@GMAIL.COM',
        email_institucional: 'ALNEDO18@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26201',
        id_personas: '26203',
        primer_nombre: 'ANDRES',
        segundo_nombre: 'RICARDO',
        sexo: 'M',
        primer_apellido: 'MOGOLLON',
        segundo_apellido: 'CARRILLO',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1093782211',
        firstName: 'ANDRES RICARDO',
        lastName: 'MOGOLLON CARRILLO',
        role: 'Estudiante',
        mail: 'ANDRESRMOGOLLON23@GMAIL.COM',
        email_institucional: 'ANDRESRMOGOLLON23@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26226',
        id_personas: '26228',
        primer_nombre: 'HAROL',
        segundo_nombre: 'DAVID',
        sexo: 'M',
        primer_apellido: 'AMAYA',
        segundo_apellido: 'MAESTRE',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1006790601',
        firstName: 'HAROL DAVID',
        lastName: 'AMAYA MAESTRE',
        role: 'Estudiante',
        mail: '',
        email_institucional: 'MAESTREHAROL1@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26293',
        id_personas: '26295',
        primer_nombre: 'JAIDER',
        segundo_nombre: 'ANDRES',
        sexo: 'M',
        primer_apellido: 'BRACHO',
        segundo_apellido: 'MEJIA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1006735804',
        firstName: 'JAIDER ANDRES',
        lastName: 'BRACHO MEJIA',
        role: 'Estudiante',
        mail: 'JAIDERBRACHO066@GMAIL.COM',
        email_institucional: 'JAIDERBRACHO066@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26414',
        id_personas: '26416',
        primer_nombre: 'JHONNY',
        segundo_nombre: 'LUIS',
        sexo: 'M',
        primer_apellido: 'BATISTA',
        segundo_apellido: 'ALGUERO',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1192790064',
        firstName: 'JHONNY LUIS',
        lastName: 'BATISTA ALGUERO',
        role: 'Estudiante',
        mail: 'JHONYALGUERO7@GMAIL.COM',
        email_institucional: 'JHONYALGUERO7@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26364',
        id_personas: '26366',
        primer_nombre: 'OROSMAN',
        segundo_nombre: 'JOEL',
        sexo: 'M',
        primer_apellido: 'CUELLO',
        segundo_apellido: 'CHINCHIA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1121330036',
        firstName: 'OROSMAN JOEL',
        lastName: 'CUELLO CHINCHIA',
        role: 'Estudiante',
        mail: '',
        email_institucional: 'JOELCUELLO537@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26411',
        id_personas: '26413',
        primer_nombre: 'ANDRES',
        segundo_nombre: 'FABIAN',
        sexo: 'M',
        primer_apellido: 'HERNANDEZ',
        segundo_apellido: 'FRIAS',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1006680597',
        firstName: 'ANDRES FABIAN',
        lastName: 'HERNANDEZ FRIAS',
        role: 'Estudiante',
        mail: 'ANDRES_HERNANDEZ0812@HOTMAIL.COM',
        email_institucional: 'ANDRES_HERNANDEZ0812@HOTMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26316',
        id_personas: '26318',
        primer_nombre: 'YEIDER',
        segundo_nombre: 'ENRIQUE',
        sexo: 'M',
        primer_apellido: 'BRITO',
        segundo_apellido: 'MEJIA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1120242092',
        firstName: 'YEIDER ENRIQUE',
        lastName: 'BRITO MEJIA',
        role: 'Estudiante',
        mail: 'YEINERBRITO0305@GMAIL.COM',
        email_institucional: 'YEINERBRITO0305@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '25973',
        id_personas: '25977',
        primer_nombre: 'HADID',
        segundo_nombre: 'SAID',
        sexo: 'M',
        primer_apellido: 'DAZA',
        segundo_apellido: 'BALASNOA',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1192772365',
        firstName: 'HADID SAID',
        lastName: 'DAZA BALASNOA',
        role: 'Estudiante',
        mail: 'HADIDSAIDDAZABALASNOA@GMAIL.COM',
        email_institucional: 'HADIDSAIDDAZABALASNOA@GMAIL.COM',
        token: '',
    },
    {
        id_pernatural: '26322',
        id_personas: '26324',
        primer_nombre: 'ALAN',
        segundo_nombre: 'LEONARDO',
        sexo: 'M',
        primer_apellido: 'DAZA',
        segundo_apellido: 'ALVAREZ',
        password: 'U2FsdGVkX19kHTX/IwotRJIeHlUMAVXe3hkQY1aYIOY=',
        username: '1122396380',
        firstName: 'ALAN LEONARDO',
        lastName: 'DAZA ALVAREZ',
        role: 'Estudiante',
        mail: 'ALANDAZALVAREZ2004@GMAIL.COM',
        email_institucional: 'ALANDAZALVAREZ2004@GMAIL.COM',
        token: '',
    },
];
export default users;
